import { Flag } from '../../types/general';

export const CREATURE_TYPE_FLAGS: Flag[] = [
  { bit: 0,  name: 'TAMEABLE_PET - Makes the mob tameable (must also be a beast and have family set) 可驯养宠物-使怪物可以驯养(必须是野兽并且有家庭设置)' },
  { bit: 1,  name: 'GHOST_VISIBLE - Creature are also visible for not alive player. 幽灵可见-生物也可以在未活着的玩家可见。' },
  { bit: 2,  name: 'BOSS_MOB - Changes creature’s visible level to "??" in the creature’s portrait - Immune to Knockback. BOSS暴怒-将该生物肖像的可见等级改为“??”-对击退免疫。' },
  { bit: 3,  name: 'DO_NOT_PLAY_WOUND_PARRY_ANIMATION 不播放伤口招架动画' },
  { bit: 4,  name: 'HIDE_FACTION_TOOLTIP 隐藏派系工具提示' },
  { bit: 5,  name: 'UNK5' },
  { bit: 6,  name: 'SPELL_ATTACKABLE 拼写可腐蚀的' },
  { bit: 7,  name: 'CAN_INTERACT_WHILE_DEAD - Player can interact with the creature if its dead (not player dead) 死亡时可以互动-玩家可以与死亡的生物互动(不是玩家死亡)' },
  { bit: 8,  name: 'HERB_SKINNING_SKILL - Makes mob herbable 药草剥皮技能-使暴民变得温顺' },
  { bit: 9,  name: 'MINING_SKINNING_SKILL - Makes mob minable 采矿剥皮技能-使怪物可以开采' },
  { bit: 10, name: 'DO_NOT_LOG_DEATH - Does not combatlog death. 不记录死亡-不战斗记录死亡。' },
  { bit: 11, name: 'MOUNTED_COMBAT_ALLOWED - Creature can remain mounted when entering combat 允许骑乘战斗-生物在进入战斗状态时可以保持骑乘状态' },
  { bit: 12, name: 'CAN_ASSIST - Can assist any player in combat if in range 可以协助-可以协助任何玩家在战斗中，如果在射程内' },
  { bit: 13, name: 'IS_PET_BAR_USED 使用宠物酒吧吗?' },
  { bit: 14, name: 'MASK_UID 面具UID' },
  { bit: 15, name: 'ENGINEERING_SKINNING_SKILL - Makes mob lootable by engineer 工程剥皮技能-使暴民可被工程师掠夺' },
  { bit: 16, name: 'EXOTIC_PET - Tamable as an exotic pet. Normal tamable flag must also be set. 外来宠物-可驯养的外来宠物。还必须设置普通可篡改标志。' },
  { bit: 17, name: 'USE_DEFAULT_COLLISION_BOX  使用默认的冲突框' },
  { bit: 18, name: 'IS_SIEGE_WEAPON 是攻城武器' },
  { bit: 19, name: 'CAN_COLLIDE_WITH_MISSILES - Projectiles can collide with this creature - interacts with TARGET_DEST_TRAJ 能与导弹碰撞-抛射物能与此生物碰撞-能与目标碰撞' },
  { bit: 20, name: 'HIDE_NAME_PLATE  隐藏铭牌' },
  { bit: 21, name: 'DO_NOT_PLAY_MOUNTED_ANIMATIONS 不播放安装的动画' },
  { bit: 22, name: 'IS_LINK_ALL 是链接' },
  { bit: 23, name: 'INTERACT_ONLY_WITH_CREATOR 只与造物主互动' },
  { bit: 24, name: 'DO_NOT_PLAY_UNIT_EVENT_SOUNDS 不播放单位事件声音' },
  { bit: 25, name: 'HAS_NO_SHADOW_BLOB 没有阴影斑点' },
  { bit: 26, name: 'TREAT_AS_RAID_UNIT 视为RAID单元' },
  { bit: 27, name: 'FORCE_GOSSIP 对话' },
  { bit: 28, name: 'DO_NOT_SHEATHE 不包装' },
  { bit: 29, name: 'DO_NOT_TARGET_ON_INTERACTION 不以互动为目标' },
  { bit: 30, name: 'DO_NOT_RENDER_OBJECT_NAME 不呈现对象名称' },
  { bit: 31, name: 'UNIT_IS_QUEST_BOSS 任务领导单位' },
];
