import { Flag } from '../../types/general';

export const ITEM_FLAGS: Flag[] = [
  { bit: 0,  name: 'NO_PICKUP 不能捡取' },
  { bit: 1,  name: 'CONJURED 被召唤的' },
  { bit: 2,  name: 'HAS_LOOT - Item can be right clicked to open its loot 可以右击打开' },
  { bit: 3,  name: 'HEROIC_TOOLTIP - Makes green "Heroic" text appear on item 使绿色的“英雄”文字出现在物品上' },
  { bit: 4,  name: 'DEPRECATED - Cannot equip or use 已弃用-不能装备或使用' },
  { bit: 5,  name: 'NO_USER_DESTROY - Item can not be destroyed, except by using a spell 物品不能被摧毁，除非使用法术' },
  { bit: 6,  name: 'PLAYERCAST - Item\'s spells are castable by players 玩家施放-物品的法术可以由玩家施放' },
  { bit: 7,  name: 'NO_EQUIP_COOLDOWN No default 30 seconds cooldown when equipped 装备时没有默认的30秒冷却时间' },
  { bit: 8,  name: 'MULTI_LOOT_QUEST' },
  { bit: 9,  name: 'IS_WRAPPER - Item can wrap other items IS_WRAPPER -物品可以包装其他物品' },
  { bit: 10, name: 'USES_RESOURCES USES_RESOURCES' },
  { bit: 11, name: 'MULTI_DROP - Looting this item does not remove it from available loot 此物品不会从可用的战利品中移除' },
  { bit: 12, name: 'ITEM_PURCHASE_RECORD - Item can be returned to the vendor for its original extended cost ITEM_PURCHASE_RECORD——可以将商品返还给供应商以支付其原始的延期费用' },
  { bit: 13, name: 'PETITION - Item is a guild or arena charter 物品是公会或竞技场的章程' },
  { bit: 14, name: 'HAS_TEXT - Only readable items have this' },
  { bit: 15, name: 'NO_DISENCHANT NO_DISENCHANT' },
  { bit: 16, name: 'REAL_DURATION REAL_DURATION' },
  { bit: 17, name: 'NO_CREATOR NO_CREATOR' },
  { bit: 18, name: 'IS_PROSPECTABLE IS_PROSPECTABLE' },
  { bit: 19, name: 'UNIQUE_EQUIPPABLE - You can only equip one of these items UNIQUE_EQUIPPABLE - 装备唯一' },
  { bit: 20, name: 'IGNORE_FOR_AURAS IGNORE_FOR_AURAS' },
  { bit: 21, name: 'IGNORE_DEFAULT_ARENA_RESTRICTIONS - Item can be used during an arena match - 物品可以在竞技场比赛中使用' },
  { bit: 22, name: 'NO_DURABILITY_LOSS NO_DURABILITY_LOSS' },
  { bit: 23, name: 'USE_WHEN_SHAPESHIFTED - Item can be used in shapeshift forms - 物品可以在变形状态下使用' },
  { bit: 24, name: 'HAS_QUEST_GLOW HAS_QUEST_GLOW' },
  { bit: 25, name: 'HIDE_UNUSABLE_RECIPE - Profession recipes: can only be looted if you meet requirements and don\'t already know it 职业配方:只有在你满足要求并且不知道的情况下才会掉落' },
  { bit: 26, name: 'NOT_USEABLE_IN_ARENA - Item cannot be used in arena 不能在竞技场中使用物品' },
  { bit: 27, name: 'IS_BOUND_TO_ACCOUNT - Item binds to account and can be sent only to your own characters 帐户绑定，只能发送给你自己的角色' },
  { bit: 28, name: 'NO_REAGENT_COST NO_REAGENT_COST' },
  { bit: 29, name: 'IS_MILLABLE IS_MILLABLE' },
  { bit: 30, name: 'REPORT_TO_GUILD_CHAT REPORT_TO_GUILD_CHAT' },
  { bit: 31, name: 'NO_PROGRESSIVE_LOOT NO_PROGRESSIVE_LOOT' },
];

// ItemFlags values
export enum ITEM_FLAG {
  CONJURED         = 0x00000002,
  OPENABLE         = 0x00000004,
  HEROIC           = 0x00000008,
  DEPRECATED       = 0x00000010,
  INDESTRUCTIBLE   = 0x00000020,
  NO_EQUIPCD       = 0x00000080,
  PARTYLOOT        = 0x00000800,
  REFUNDABLE       = 0x00001000,
  PROSPECTABLE     = 0x00040000,
  UNIQUEEQUIPPED   = 0x00080000,
  USABLE_ARENA     = 0x00200000,
  USABLE_SHAPED    = 0x00800000,
  SMARTLOOT        = 0x02000000,
  ACCOUNTBOUND     = 0x08000000,
  MILLABLE         = 0x20000000,
}
