import { Flag } from '../../types/general';

export const MECHANIC_IMMUNE_MASK: Flag[] = [
  { bit: 0,  name: 'CHARM 魅力' },
  { bit: 1,  name: 'DISORIENTED 迷失方向' },
  { bit: 2,  name: 'DISARM 解除' },
  { bit: 3,  name: 'DISTRACT 分散' },
  { bit: 4,  name: 'FEAR 恐惧' },
  { bit: 5,  name: 'GRIP - Death Grip and similar effects 握紧-死亡握紧和类似的效果' },
  { bit: 6,  name: 'ROOT 根' },
  { bit: 7,  name: 'SLOW_ATTACK 缓慢的攻击' },
  { bit: 8,  name: 'SILENCE 沉默' },
  { bit: 9,  name: 'SLEEP 睡眠' },
  { bit: 10, name: 'SNARE 陷阱' },
  { bit: 11, name: 'STUN 眩晕' },
  { bit: 12, name: 'FREEZE 冻结' },
  { bit: 13, name: 'KNOCKOUT - Incapacitate effects such as Repentance (Paladin) 击昏-丧失能力的效果，如悔改(圣骑士)' },
  { bit: 14, name: 'BLEED 流血' },
  { bit: 15, name: 'BANDAGE - Healing 绷带,愈合' },
  { bit: 16, name: 'POLYMORPH 变形术' },
  { bit: 17, name: 'BANISH 消除' },
  { bit: 18, name: 'SHIELD 盾' },
  { bit: 19, name: 'SHACKLE - Shackle Undead only 束缚-只束缚不死族' },
  { bit: 20, name: 'MOUNT - Any effect that summons a mount 坐骑-任何可以召唤坐骑的效果' },
  { bit: 21, name: 'INFECTED - e.g. Frost Fever, Blood Plague etc.. 受感染-例如霜冻热、血瘟等。' },
  { bit: 22, name: 'TURN - e.g. Turn Evil 变坏' },
  { bit: 23, name: 'HORROR - e.g. Death Coil (Warlock) 恐怖-例如死亡缠绕(术士)' },
  { bit: 24, name: 'INVULNERABILITY - Forbearance, Nether Protection, Diplomatic Immunity only 无懈可击-容忍，地狱保护，外交豁免权' },
  { bit: 25, name: 'INTERRUPT 中断' },
  { bit: 26, name: 'DAZE 眼花缭乱' },
  { bit: 27, name: 'DISCOVERY - Any Create Item effect 发现-任何创造物品的效果' },
  { bit: 28, name: 'IMMUNE_SHIELD - e.g. Divine Shield, Ice Block, Hand of Protection 免疫盾牌-例如神圣之盾，冰挡，保护之手' },
  { bit: 29, name: 'SAPPED 削弱了' },
  { bit: 30, name: 'ENRAGED 激怒了' },
];
