import { Flag } from '../../types/general';

export const NPC_FLAGS: Flag[] = [
   { bit: 0,  name: 'GOSSIP - If creature has more gossip options, add this flag to bring up a menu.  对话-如果生物有更多的对话选项，添加这个标志到菜单中。' },
   { bit: 1,  name: 'QUESTGIVER - Any creature giving or taking quests needs to have this flag.  任务给予者-任何给予或接受任务的生物都需要这个标志。' },
   { bit: 2,  name: 'UNK1' },
   { bit: 3,  name: 'UNK2' },
   { bit: 4,  name: 'TRAINER - Allows the creature to have a trainer list to teach spells  训练师-允许该生物有一个训练师列表来教授法术' },
   { bit: 5,  name: 'TRAINER_CLASS 培训类' },
   { bit: 6,  name: 'TRAINER_PROFESSION 职业培训师' },
   { bit: 7,  name: 'VENDOR - Any creature selling items needs to have this flag.  商人-任何出售物品的生物都需要有这个标志。' },
   { bit: 8,  name: 'VENDOR_AMMO  弹药供应商' },
   { bit: 9,  name: 'VENDOR_FOOD  食物供应商' },
   { bit: 10, name: 'VENDOR_POISON  毒药供应商' },
   { bit: 11, name: 'VENDOR_REAGENT  药剂供应商' },
   { bit: 12, name: 'REPAIR - Creatures with this flag can repair items.  修复-有此标志的生物可以修复物品。' },
   { bit: 13, name: 'FLIGHTMASTER - Any creature serving as flight master has this.  飞行大师-任何担任飞行大师的生物都有这个技能。' },
   { bit: 14, name: 'SPIRITHEALER - Makes the creature invisible to alive characters and has the resurrect function.  使生物对活着的角色不可见，并且有复活的功能。' },
   { bit: 15, name: 'SPIRITGUIDE  灵魂向导' },
   { bit: 16, name: 'INNKEEPER - Creatures with this flag can set hearthstone locations.  拥有此旗帜的生物可以设置炉石的位置。' },
   { bit: 17, name: 'BANKER - Creatures with this flag can show the bank  银行家-持有此旗帜的生物可以显示银行 ' },
   { bit: 18, name: 'PETITIONER 请愿者' },
   { bit: 19, name: 'TABARDDESIGNER - Allows the designing of guild tabards.  允许设计公会标签。' },
   { bit: 20, name: 'BATTLEMASTER - Creatures with this flag port players to battlegrounds.  战斗大师-有此旗帜的生物可以让玩家进入战场。' },
   { bit: 21, name: 'AUCTIONEER - Allows creature to display auction list.  允许生物显示拍卖列表。' },
   { bit: 22, name: 'STABLEMASTER - Has the option to stable pets for hunters.  猎人可以选择养宠物。' },
   { bit: 23, name: 'GUILD_BANKER  公会的银行家' },
   { bit: 24, name: 'SPELLCLICK - Needs data on npc_spellclick_spells table  需要npc_spellclick_spell表上的数据' },
   { bit: 25, name: 'PLAYER_VEHICLE - players with mounts that have vehicle data should have it set  拥有车辆数据的坐骑的玩家应该设置它' },
   { bit: 26, name: 'MAILBOX - NPC will act like a mailbox (opens mailbox with right-click)  邮箱- NPC将扮演邮箱的角色(用右键单击打开邮箱)' },
];
