import { Flag } from '../../types/general';

export const UNIT_FLAGS: Flag[] = [
  { bit: 0,  name: 'SERVER_CONTROLLED 服务器控制' },
  { bit: 1,  name: 'NON_ATTACKABLE 非可腐蚀的' },
  { bit: 2,  name: 'DISABLE_MOVE 禁用移动' },
  { bit: 3,  name: 'PVP_ATTACKABLE - allow apply pvp rules to attackable state in addition to faction dependent state PVP可攻击-允许应用PVP规则到可攻击的状态，除了阵营依赖状态' },
  { bit: 4,  name: 'RENAME 重命名' },
  { bit: 5,  name: 'PREPARATION - don\'t take reagents for spells with SPELL_ATTR5_NO_REAGENT_WHILE_PREP 准备-在准备法术ATTR5法术时不要使用试剂' },
  { bit: 6,  name: 'UNK_6 - not sure what it does, but it is needed to cast nontriggered spells in smart_scripts 灌篮6 -不知道它做了什么，但是它需要在智能脚本中施放非触发法术' },
  { bit: 7,  name: 'NOT_ATTACKABLE_1 不是可腐蚀的1' },
  { bit: 8,  name: 'IMMUNE_TO_PC - disables combat/assistance with PlayerCharacters (PC) 免疫PC -禁用玩家角色的战斗/协助(PC)' },
  { bit: 9,  name: 'IMMUNE_TO_NPC - disables combat/assistance with NonPlayerCharacters (NPC) 对NPC免疫-禁用非玩家角色的战斗/协助(NPC)' },
  { bit: 10, name: 'LOOTING - loot animation 掠夺-掠夺动画' },
  { bit: 11, name: 'PET_IN_COMBAT 宠物在战斗中' },
  { bit: 12, name: 'PVP PVP' },
  { bit: 13, name: 'SILENCED - Can’t cast spells 沉默-不能施展法术' },
  { bit: 14, name: 'UNK_14' },
  { bit: 15, name: 'UNK_15 - Only Swim  扣篮15 -只游泳' },
  { bit: 16, name: 'UNK_16 - No Attack 2 扣篮16 -无攻击2' },
  { bit: 17, name: 'PACIFIED - Creature will not attack 平定-生物不会攻击' },
  { bit: 18, name: 'STUNNED 惊呆了' },
  { bit: 19, name: 'IN_COMBAT 在战斗中' },
  { bit: 20, name: 'TAXI_FLIGHT - disable casting at client side spell not allowed by taxi flight  滑行飞行-禁用滑行飞行不能在客户端施放的法术' },
  { bit: 21, name: 'DISARMED - disable melee spells casting 解除武装-使近战技能无效' },
  { bit: 22, name: 'CONFUSED 困惑' },
  { bit: 23, name: 'FLEEING - feared 逃离,担心' },
  { bit: 24, name: 'PLAYER_CONTROLLED - used in spell Eyes of the Beast for pet 玩家控制-在“野兽之眼”法术中用于宠物' },
  { bit: 25, name: 'NOT_SELECTABLE - Can’t be selected by mouse or with /target {name} command. 不可选择-无法通过鼠标或/目标{name}命令选择。' },
  { bit: 26, name: 'SKINNABLE 皮肤' },
  { bit: 27, name: 'MOUNT - The client seems to handle it perfectly. Also used when making custom mounts. MOUNT -客户端似乎能完美地处理它。也用于定制坐骑。' },
  { bit: 28, name: 'UNK_28 - PreventKneelingWhenLooting 扣篮28 -抢篮板时防止下跪' },
  { bit: 29, name: 'UNK_29 - Used in Feign Death spell or NPC will play dead 灌篮29 -假装死亡或NPC将装死' },
  { bit: 30, name: 'SHEATHE 包装' },
  { bit: 31, name: 'UNK_31' },
];
