import { Option } from '../../types/general';

export const CREATURE_FAMILY: Option[] = [
  { value: 0,  name: 'None 没有一个' },
  { value: 1,  name: 'Wolf 狼' },
  { value: 2,  name: 'Cat 猫' },
  { value: 3,  name: 'Spider 蜘蛛' },
  { value: 4,  name: 'Bear 熊' },
  { value: 5,  name: 'Boar 野猪' },
  { value: 6,  name: 'Crocolisk' },
  { value: 7,  name: 'Carrion Bird 以腐肉为食的鸟类' },
  { value: 8,  name: 'Crab 蟹' },
  { value: 9,  name: 'Gorilla 大猩猩' },
  { value: 11, name: 'Raptor 猛禽' },
  { value: 12, name: 'Tallstrider' },
  { value: 15, name: 'Felhunter 地狱犬' },
  { value: 16, name: 'Voidwalker 虚空行者' },
  { value: 17, name: 'Succubus 女妖' },
  { value: 19, name: 'Doomguard 恶魔守卫' },
  { value: 20, name: 'Scorpid' },
  { value: 21, name: 'Turtle 乌龟' },
  { value: 23, name: 'Imp 小鬼' },
  { value: 24, name: 'Bat 蝙蝠' },
  { value: 25, name: 'Hyena 土狼' },
  { value: 26, name: 'Bird of Prey 猛禽' },
  { value: 27, name: 'Wind Serpent 风蛇' },
  { value: 28, name: 'Remote Control 远程控制' },
  { value: 29, name: 'Felguard 恶魔守卫' },
  { value: 30, name: 'Dragonhawk 龙鹰' },
  { value: 31, name: 'Ravager 劫掠者' },
  { value: 32, name: 'Warp Stalker 经跟踪狂' },
  { value: 33, name: 'Sporebat 孢子蝙蝠' },
  { value: 34, name: 'Nether Ray 虚空雷' },
  { value: 35, name: 'Serpent 蛇' },
  { value: 37, name: 'Moth 蛾' },
  { value: 38, name: 'Chimaera 嵌合体' },
  { value: 39, name: 'Devilsaur 恶魔本身' },
  { value: 40, name: 'Ghoul 食尸鬼' },
  { value: 41, name: 'Silithid' },
  { value: 42, name: 'Worm 蠕虫' },
  { value: 43, name: 'Rhino 犀牛' },
  { value: 44, name: 'Wasp 黄蜂' },
  { value: 45, name: 'Core Hound 核心猎犬' },
  { value: 46, name: 'Spirit Beast 灵兽' },
];
