import { Option } from '../../types/general';

export const INVENTORY_TYPE: Option[] = [
  { value: 0,  name: 'NON_EQUIP' },
  { value: 1,  name: 'HEAD 头' },
  { value: 2,  name: 'NECK 颈' },
  { value: 3,  name: 'SHOULDERS 肩' },
  { value: 4,  name: 'BODY 身体' },
  { value: 5,  name: 'CHEST 胸' },
  { value: 6,  name: 'WAIST 腰' },
  { value: 7,  name: 'LEGS 腿' },
  { value: 8,  name: 'FEET 脚' },
  { value: 9,  name: 'WRISTS 手腕' },
  { value: 10, name: 'HANDS 手' },
  { value: 11, name: 'FINGER 手指' },
  { value: 12, name: 'TRINKET 饰品' },
  { value: 13, name: 'WEAPON 武器' },
  { value: 14, name: 'SHIELD 盾' },
  { value: 15, name: 'RANGED' },
  { value: 16, name: 'CLOAK 披风' },
  { value: 17, name: '2HWEAPON 双手武器' },
  { value: 18, name: 'BAG 袋子' },
  { value: 19, name: 'TABARD 粗呢大衣' },
  { value: 20, name: 'ROBE 战袍' },
  { value: 21, name: 'WEAPONMAINHAND 主手武器' },
  { value: 22, name: 'WEAPONOFFHAND 副手武器' },
  { value: 23, name: 'HOLDABL' },
  { value: 24, name: 'AMMO 弹药' },
  { value: 25, name: 'THROWN 投掷' },
  { value: 26, name: 'RANGEDRIGHT 远程' },
  { value: 27, name: 'QUIVER 箭袋' },
  { value: 28, name: 'RELIC 圣物' },
];
