import { Option } from '../../types/general';

// todo
export const STAT_TYPE: Option[] = [
  { value: 0,  name: 'MANA 魔法' },
  { value: 1,  name: 'HEALTH 生命' },
  { value: 3,  name: 'AGILITY 敏捷性' },
  { value: 4,  name: 'STRENGTH 强度' },
  { value: 5,  name: 'INTELLECT 智力' },
  { value: 6,  name: 'SPIRIT 精神' },
  { value: 7,  name: 'STAMINA 耐力' },
  { value: 12, name: 'DEFENSE_SKILL_RATING 防御技能等级' },
  { value: 13, name: 'DODGE_RATING 道奇等级' },
  { value: 14, name: 'PARRY_RATING 帕里等级' },
  { value: 15, name: 'BLOCK_RATING 块等级' },
  { value: 16, name: 'HIT_MELEE_RATING 近战等级' },
  { value: 17, name: 'HIT_RANGED_RATING 攻击范围等级' },
  { value: 18, name: 'HIT_SPELL_RATING 法术等级' },
  { value: 19, name: 'CRIT_MELEE_RATING 暴击近战等级' },
  { value: 20, name: 'CRIT_RANGED_RATING 暴击远程等级' },
  { value: 21, name: 'CRIT_SPELL_RATING 暴击法术等级' },
  { value: 22, name: 'HIT_TAKEN_MELEE_RATING 近战命中等级' },
  { value: 23, name: 'HIT_TAKEN_RANGED_RATING 击中射程等级' },
  { value: 24, name: 'HIT_TAKEN_SPELL_RATING 命中法术等级' },
  { value: 25, name: 'CRIT_TAKEN_MELEE_RATING 暴击造成近身攻击等级' },
  { value: 26, name: 'CRIT_TAKEN_RANGED_RATING 远程致命一击' },
  { value: 27, name: 'CRIT_TAKEN_SPELL_RATING 施法等级造成致命一击' },
  { value: 28, name: 'HASTE_MELEE_RATING 匆忙近战等级' },
  { value: 29, name: 'HASTE_RANGED_RATING 匆忙远程等级' },
  { value: 30, name: 'HASTE_SPELL_RATING 匆忙法术等级' },
  { value: 31, name: 'HIT_RATING 命中等级' },
  { value: 32, name: 'CRIT_RATING 暴击等级' },
  { value: 33, name: 'HIT_TAKEN_RATING 攻击等级' },
  { value: 34, name: 'CRIT_TAKEN_RATING 暴击等级' },
  { value: 35, name: 'RESILIENCE_RATING 韧性等级' },
  { value: 36, name: 'HASTE_RATING 急速等级' },
  { value: 37, name: 'EXPERTISE_RATING 专业的评价' },
  { value: 38, name: 'ATTACK_POWER 攻击强度' },
  { value: 39, name: 'RANGED_ATTACK_POWER 远程攻击强度' },
  { value: 40, name: 'FERAL_ATTACK_POWER (not used as of 3.3) 野性攻击强度(3.3版本未使用)' },
  { value: 41, name: 'SPELL_HEALING_DONE 法术治疗效果' },
  { value: 42, name: 'SPELL_DAMAGE_DONE 法术伤害' },
  { value: 43, name: 'MANA_REGENERATION 法力再生' },
  { value: 44, name: 'ARMOR_PENETRATION_RATING 护甲穿透等级' },
  { value: 45, name: 'SPELL_POWER 法术强度' },
  { value: 46, name: 'HEALTH_REGEN 生命的回复' },
  { value: 47, name: 'SPELL_PENETRATION 法术穿透' },
  { value: 48, name: 'BLOCK_VALUE 块价值' },
];
