import { Option } from '../../types/general';

// todo
export const STAT_TYPE: Option[] = [
  { value: 0,  name: 'MANA 魔法' },
  { value: 1,  name: 'HEALTH 生命' },
  { value: 3,  name: 'AGILITY 敏捷' },
  { value: 4,  name: 'STRENGTH 力量' },
  { value: 5,  name: 'INTELLECT 智力' },
  { value: 6,  name: 'SPIRIT 精神' },
  { value: 7,  name: 'STAMINA 耐力' },
  { value: 12, name: 'DEFENSE_SKILL_RATING 防御技能等级' },
  { value: 13, name: 'DODGE_RATING 躲闪等级' },
  { value: 14, name: 'PARRY_RATING 格挡等级' },
  { value: 15, name: 'BLOCK_RATING 盾牌格挡等级' },
  { value: 16, name: 'HIT_MELEE_RATING 近战命中率' },
  { value: 17, name: 'HIT_RANGED_RATING 远程命中率' },
  { value: 18, name: 'HIT_SPELL_RATING 法术命中率' },
  { value: 19, name: 'CRIT_MELEE_RATING 近战暴击等级' },
  { value: 20, name: 'CRIT_RANGED_RATING 远程暴击等级' },
  { value: 21, name: 'CRIT_SPELL_RATING 法术暴击等级' },
  { value: 22, name: 'HIT_TAKEN_MELEE_RATING 近战命中躲闪等级' },
  { value: 23, name: 'HIT_TAKEN_RANGED_RATING 远程命中躲闪等级' },
  { value: 24, name: 'HIT_TAKEN_SPELL_RATING 法术命中躲闪等级' },
  { value: 25, name: 'CRIT_TAKEN_MELEE_RATING 近战致命躲避等级' },
  { value: 26, name: 'CRIT_TAKEN_RANGED_RATING 远程致命躲避等级' },
  { value: 27, name: 'CRIT_TAKEN_SPELL_RATING 法术爆击躲避等级' },
  { value: 28, name: 'HASTE_MELEE_RATING 近战加速等级' },
  { value: 29, name: 'HASTE_RANGED_RATING 远程加速等级' },
  { value: 30, name: 'HASTE_SPELL_RATING 法术急速等级' },
  { value: 31, name: 'HIT_RATING 命中等级' },
  { value: 32, name: 'CRIT_RATING 暴击等级' },
  { value: 33, name: 'HIT_TAKEN_RATING 命中躲避等级' },
  { value: 34, name: 'CRIT_TAKEN_RATING 暴击躲避等级' },
  { value: 35, name: 'RESILIENCE_RATING 韧性等级' },
  { value: 36, name: 'HASTE_RATING 急速等级' },
  { value: 37, name: 'EXPERTISE_RATING 专业技能等级' },
  { value: 38, name: 'ATTACK_POWER 攻击强度' },
  { value: 39, name: 'RANGED_ATTACK_POWER 远程攻击强度' },
  { value: 40, name: 'FERAL_ATTACK_POWER (not used as of 3.3) 猫、熊、巨熊和Moonkin形态的攻击强度(3.3版本未使用)' },
  { value: 41, name: 'SPELL_HEALING_DONE 法术治疗效果' },
  { value: 42, name: 'SPELL_DAMAGE_DONE 法术伤害' },
  { value: 43, name: 'MANA_REGENERATION 法力回复' },
  { value: 44, name: 'ARMOR_PENETRATION_RATING 护甲穿透等级' },
  { value: 45, name: 'SPELL_POWER 法术能量' },
  { value: 46, name: 'HEALTH_REGEN 生命回复' },
  { value: 47, name: 'SPELL_PENETRATION 法术穿透' },
  { value: 48, name: 'BLOCK_VALUE 盾牌格挡值' },
];
