import { Option } from '../../types/general';

export const TOTEM_CATEGORY: Option[] = [
  { value: 1,   name: 'Skinning Knife (OLD) 削皮刀(旧)' },
  { value: 2,   name: 'Earth Totem 图腾' },
  { value: 3,   name: 'Air Totem 空气图腾' },
  { value: 4,   name: 'Fire Totem 火图腾' },
  { value: 5,   name: 'Water Totem 水图腾' },
  { value: 6,   name: 'Runed Copper Rod 符文铜杆' },
  { value: 7,   name: 'Runed Silver Rod 符文银杆' },
  { value: 8,   name: 'Runed Golden Rod 符文金棒' },
  { value: 9,   name: 'Runed Truesilver Rod 符文Truesilver杆' },
  { value: 10,  name: 'Runed Arcanite Rod 符文单钾芒硝杆' },
  { value: 11,  name: 'Mining Pick (OLD) 矿业选择(旧)' },
  { value: 12,  name: 'Philosopher\'s Stone 哲学家的石头' },
  { value: 13,  name: 'Blacksmith Hammer (OLD) 铁匠锤(旧)' },
  { value: 14,  name: 'Arclight Spanner 电弧光扳手' },
  { value: 15,  name: 'Gyromatic Micro-Adjustor' },
  { value: 21,  name: 'Master Totem 主图腾' },
  { value: 41,  name: 'Runed Fel Iron Rod 符文恶魔铁棒' },
  { value: 62,  name: 'Runed Adamantite Rod 符文Adamantite杆' },
  { value: 63,  name: 'Runed Eternium Rod 符文Eternium杆' },
  { value: 81,  name: 'Hollow Quill 空心套筒' },
  { value: 101, name: 'Runed Azurite Rod 符文蓝铜矿杆' },
  { value: 121, name: 'Virtuoso Inking Set 艺术大师署名集' },
  { value: 141, name: 'Drums 鼓' },
  { value: 161, name: 'Gnomish Army Knife 侏儒的军刀' },
  { value: 162, name: 'Blacksmith Hammer 铁匠锤' },
  { value: 165, name: 'Mining Pick 矿山选' },
  { value: 166, name: 'Skinning Knife 削皮刀' },
  { value: 167, name: 'Hammer Pick 锤挑' },
  { value: 168, name: 'Bladed Pickaxe 鹤嘴锄' },
  { value: 169, name: 'Flint and Tinder 火石和火绒' },
  { value: 189, name: 'Runed Cobalt Rod 符文钴棒' },
  { value: 190, name: 'Runed Titanium Rod 符文钛棒' },
];

